/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
*/
package NumberGuess;

/**
 *
 * @author kali-i
 */
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class PlayForm extends javax.swing.JFrame {
    
    /**
     * Creates new form PlayForm
     */
    Random R=new Random();
    int a=R.nextInt(0, 100);
    int counter=1;
    public PlayForm() {
        initComponents();

        
    }
    
    public void check(){
        int fetchInput=Integer.parseInt(this.jTextField1.getText());
        updateResult(fetchInput,a);
        if(fetchInput==a){
              VisibleHearts();
        }
        else{
            switch(counter){
                case 1 ->{
                    this.jButton14.setVisible(false);
                }
                case 2 ->{
                    this.jButton6.setVisible(false);
                }
                case 3 ->{
                    this.jButton4.setVisible(false);
                }
                case 4 ->{
                    this.jButton16.setVisible(false);
                }
                case 5 ->{
                    this.jButton17.setVisible(false);
                }
                case 6 ->{
                    this.jButton15.setVisible(false);
                }
                case 7 ->{
                    this.jButton19.setVisible(false);
                }
                case 8 ->{
                    this.jButton20.setVisible(false);
                }
                case 9 ->{
                    this.jButton18.setVisible(false);
                }
                case 10 ->{
                    this.jButton21.setVisible(false);
                }
                case 11 ->{
                 JOptionPane.showMessageDialog(
            null,                   
            "GAME OVER\nYour Total Score is : "+this.jLabel3.getText(), 
            "Done",          // Dialog title
            JOptionPane.INFORMATION_MESSAGE
        );
                 CustomDialogExample.openCustomDialog();
                 if(CustomDialogExample.result){
                     this.jLabel3.setText("0");
                     VisibleHearts();
                   
                 }
                }
                
            }
            counter++;
        }
        
    }
    
    public void VisibleHearts(){
                    this.jButton14.setVisible(true); 
                    this.jButton6.setVisible(true);
                    this.jButton4.setVisible(true);
                    this.jButton16.setVisible(true);
                    this.jButton17.setVisible(true);
                    this.jButton15.setVisible(true);
                    this.jButton19.setVisible(true);
                    this.jButton20.setVisible(true);
                    this.jButton18.setVisible(true);
                    this.jButton21.setVisible(true);
                    a=R.nextInt(0, 100);
                    counter=1;
         
    }
    

    public void updateResult(int a,int b){
    if(a-b==0){

           jButton1.setText(String.valueOf(a));
            
            String data=this.jLabel3.getText();
            int a2=Integer.parseInt(data);
            a2+=5;
             this.jLabel3.setText(String.valueOf(a2));
            this.jLabel4.setText("Correct");
            JOptionPane.showMessageDialog(
            null,                   
            "You Guess Correctly\nYou got +5 points", 
            "Done",          // Dialog title
            JOptionPane.INFORMATION_MESSAGE
        );
                       this.jLabel4.setText("Result");
            jButton1.setText(String.valueOf("*"));
           
    }
    
    else if (a-b<0 && a-b>-10 ){
        this.jLabel4.setText("Low");
    }    
     else if (a-b<-10 ){
        this.jLabel4.setText("Too Low");
    }   
    
      else if (a-b>0 && a-b<10 ){
        this.jLabel4.setText("High");
    }    
     else if (a-b>10 ){
        this.jLabel4.setText("Too High");
    }   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setText("NUMBER GUESS GAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 6, 220, -1));

        jButton1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton1.setText("*");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 384, 90, 60));

        jTextField1.setToolTipText("Enter Your guess number");
        jTextField1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 503, 177, 33));

        jButton2.setText("Guess");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 554, 140, 40));

        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("j");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setText("\u2665");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 342, 47, 36));

        jButton6.setForeground(new java.awt.Color(255, 0, 0));
        jButton6.setText("j");
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setText("\u2665");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 342, 47, 36));

        jButton14.setForeground(new java.awt.Color(255, 0, 0));
        jButton14.setText("j");
        jButton14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setText("\u2665");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 342, 47, 36));

        jButton15.setForeground(new java.awt.Color(255, 0, 0));
        jButton15.setText("j");
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setText("\u2665");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 342, 47, 36));

        jButton16.setForeground(new java.awt.Color(255, 0, 0));
        jButton16.setText("j");
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setText("\u2665");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 342, 47, 36));

        jButton17.setForeground(new java.awt.Color(255, 0, 0));
        jButton17.setText("j");
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setText("\u2665");
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 342, 47, 36));

        jButton18.setForeground(new java.awt.Color(255, 0, 0));
        jButton18.setText("j");
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setText("\u2665");
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 342, 47, 36));

        jButton19.setForeground(new java.awt.Color(255, 0, 0));
        jButton19.setText("j");
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setText("\u2665");
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 342, 47, 36));

        jButton20.setForeground(new java.awt.Color(255, 0, 0));
        jButton20.setText("j");
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.setText("\u2665");
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 342, 47, 36));

        jButton21.setForeground(new java.awt.Color(255, 0, 0));
        jButton21.setText("j");
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton21.setText("\u2665");
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 342, 47, 36));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setText("Score");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 314, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setText("0");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 314, -1, -1));

        jLabel4.setText("Result");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 456, -1, -1));

        jButton3.setIcon(new ImageIcon(this.getClass().getResource("/NumberGuess/oasis1.png")));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 75, 307, 190));

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel5.setText("OASIS INFOBYTE INTERNSHIP ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 34, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        check();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
